In [4]:
import results_deser as rd
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [5]:
accs = [rd.load_testaccs("results/results_intraclass_n2_" + str(i)) for i in range(2)]
df_ic_1 = pd.DataFrame(accs)
df_ic_1.loc["mean"] = df_ic_1.mean(axis=0)
df_ic_1

      [0.75 0.25]  [0.5 0.5]
0          59.110      53.77
1          58.240      55.79
mean       58.675      54.78

## benchmark

In [6]:
accs = [rd.load_testaccs("results/results_intraclass100_n2_" + str(i)) for i in range(2)]
df_ic100_1 = pd.DataFrame(accs)
df_ic100_1.loc["mean"] = df_ic100_1.mean(axis=0)
df_ic100_1

      [0.75 0.25]  [0.5 0.5]
0          24.130     29.630
1          24.060     26.640
mean       24.095     28.135

## benchmark